language: node_js
node_js:
 - "node"
before_install:
  - npm install -g nyc
  - npm install -g codecov
  - npm install -g istanbul
  - sudo snap install hugo
script:
  - npm run test
  - npm run report-coverage